"""Render docs/cli.md from the live Typer command tree.

The generated page is committed so it reads well on GitHub and in the
published site. ``--check`` makes CI fail when a command, argument, option,
type, default, or help string changes without regenerating the page.
"""

from __future__ import annotations

import argparse
from collections.abc import Iterator
from pathlib import Path
from typing import Any

from typer._click.core import Context, Parameter
from typer.main import get_command

from sci_rag.cli.main import app


def _one_line(value: str | None) -> str:
    return " ".join((value or "").split())


def _cell(value: Any) -> str:
    if value is None:
        return "-"
    text = _one_line(str(value))
    return text.replace("|", "\\|") or "-"


def _code(value: str) -> str:
    escaped = value.replace("`", "\\`")
    return f"`{escaped}`"


def _type_name(param: Parameter) -> str:
    parameter_type = param.type
    choices = getattr(parameter_type, "choices", None)
    if choices is not None:
        label = " | ".join(str(choice) for choice in choices)
    else:
        label = parameter_type.name or type(parameter_type).__name__
    if param.nargs == -1:
        return f"{label}, repeatable"
    if param.nargs > 1:
        return f"{label} x {param.nargs}"
    return label


def _default(param: Parameter) -> str:
    if param.required:
        return "required"
    value = param.default
    if value is None:
        return "unset"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (tuple, list)):
        return ", ".join(str(item) for item in value) or "empty"
    if callable(value):
        return "computed"
    return str(value)


def _parameter_name(param: Parameter) -> str:
    if param.param_type_name == "option":
        return ", ".join([*getattr(param, "opts", ()), *getattr(param, "secondary_opts", ())])
    return (param.human_readable_name or param.name or "argument").upper()


def _iter_commands(
    command: Any, path: tuple[str, ...] = ()
) -> Iterator[tuple[tuple[str, ...], Any]]:
    if not hasattr(command, "list_commands"):
        return
    context = Context(command, info_name=" ".join(("sci-rag", *path)))
    for name in command.list_commands(context):
        child = command.get_command(context, name)
        if child is None or child.hidden:
            continue
        child_path = (*path, name)
        yield child_path, child
        if hasattr(child, "list_commands"):
            yield from _iter_commands(child, child_path)


def _usage(command: Any, display_name: str) -> str:
    context = Context(command, info_name=display_name)
    pieces = command.collect_usage_pieces(context)
    suffix = f" {' '.join(pieces)}" if pieces else ""
    return f"$ {display_name}{suffix}"


def _purpose(command: Any) -> str:
    return _one_line(command.help or command.short_help) or "No description provided."


def render_cli_docs() -> str:
    root = get_command(app)
    commands = list(_iter_commands(root))
    lines = [
        "---",
        "title: CLI",
        "description: Every Sci RAG Kit command, argument, option, type, and default, generated from the live Typer application.",
        "---",
        "",
        "# CLI",
        "",
        "<!-- Generated by scripts/render_cli_docs.py; do not edit by hand. -->",
        "",
        "This page is generated from `src/sci_rag/cli/main.py`. Run",
        "`make docs-reference` after changing the Typer command surface.",
        "All commands run from inside the repository so relative settings,",
        "migrations, `domain/`, and data paths resolve predictably.",
        "",
        "## Command map",
        "",
        "| Command | Purpose |",
        "|---|---|",
    ]
    for path, command in commands:
        display_name = " ".join(("sci-rag", *path))
        lines.append(f"| {_code(display_name)} | {_cell(_purpose(command))} |")

    for path, command in commands:
        display_name = " ".join(("sci-rag", *path))
        lines += [
            "",
            f"## `{display_name}`",
            "",
            _purpose(command),
            "",
            "```console",
            _usage(command, display_name),
            "```",
        ]
        arguments = [param for param in command.params if param.param_type_name == "argument"]
        options = [param for param in command.params if param.param_type_name == "option"]
        if arguments:
            lines += [
                "",
                "### Arguments",
                "",
                "| Name | Type | Default | Description |",
                "|---|---|---|---|",
            ]
            for param in arguments:
                lines.append(
                    "| "
                    + " | ".join(
                        (
                            _code(_parameter_name(param)),
                            _cell(_type_name(param)),
                            _cell(_default(param)),
                            _cell(getattr(param, "help", None)),
                        )
                    )
                    + " |"
                )
        if options:
            lines += [
                "",
                "### Options",
                "",
                "| Option | Type | Default | Description |",
                "|---|---|---|---|",
            ]
            for param in options:
                lines.append(
                    "| "
                    + " | ".join(
                        (
                            _code(_parameter_name(param)),
                            _cell(_type_name(param)),
                            _cell(_default(param)),
                            _cell(param.help),
                        )
                    )
                    + " |"
                )

    lines += [
        "",
        "## Shell help is authoritative too",
        "",
        "Run `uv run sci-rag COMMAND --help` for the same current command tree",
        "in the terminal. The generated page is a browsing aid; Click remains",
        "the parser that decides whether a concrete invocation is valid.",
        "",
    ]
    return "\n".join(lines)


def _write_or_check(output: Path, page: str, *, check: bool) -> int:
    if check:
        if not output.exists() or output.read_text(encoding="utf-8") != page:
            print(f"stale generated reference: {output}; run make docs-reference")
            return 1
        print(f"up to date: {output}")
        return 0
    output.write_text(page, encoding="utf-8")
    print(f"wrote {output}")
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=Path("docs/cli.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    raise SystemExit(_write_or_check(args.output, render_cli_docs(), check=args.check))


if __name__ == "__main__":
    main()
